### ISSUE TITLE
Vector shouldn't be necessary

### ISSUE THREAD

**Issue by PatatasDelPapa** [six519/facebook_video_downloader#1]
Instead of 
```rust
let mut args: Vec<String> = env::args().collect();

if args.len() == 2 {
    let url = args.remove(1);
```
like [here](https://github.com/six519/facebook_video_downloader/blob/f5a76083d60beca991b1396a8f9cacc98f6159b0/src/main.rs#L18-L21) you could also do something like
```rust
let url = std::env::args()
    .skip(1)
    .next()
    .expect("should have one argument");
```

**Comment by six519** [comment]
Thanks for your feedback!. Updated the code just now. I'm still learning the language and just started learning it today. ;)

**Comment by PatatasDelPapa** [comment]
Great work!
If you want you could use Clap / StructOpt (or any other similar library) for command parsing, benefits include that they create a help menu and suggestions and adding features is easier to mantain
